language: php

php:
- 5.4
- 5.5
- 5.6
- 7.0
- hhvm

before_script:
- composer config -g github-oauth.github.com $GITHUB_ACCESS_TOKEN
- composer self-update
- composer require codeclimate/php-test-reporter --dev
- composer install --prefer-dist --no-interaction
